name: Go

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test & prepare coverage
        run: go test -coverprofile=coverage.out
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
